---
title: "Plot of common cells drugs"
author: "Matt Ploenzke"
date: "12/31/2019"
output: html_document:
  toc: true
  toc_float: true
  code_folding: hide 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages.
```{r}
library(tidyverse)
library(PharmacoGx)
```

Set options for the run.
```{r}
datasets <- c('CCLE','GDSC1000','gCSI','CTRPv2','FIMM')
```

Grab cells and drugs, one per study.
```{r}
rez <- list()
for (dataset in datasets) {
  print(dataset)
  load(file.path('~/Desktop/Concordance/PSets',paste(dataset,'RData',sep='.')))
  eval(parse(text = paste('tempPset <- ',dataset,sep='')))
  y_new_temp <- summarizeSensitivityProfiles(tempPset, 
                                             sensitivity.measure = 'auc_recomputed', 
                                             summary.stat = 'median', 
                                             verbose = FALSE) %>%
    as.data.frame() %>%
    rownames_to_column('drug') %>%
    as_tibble() %>% 
    gather(key='cell',value='value',-drug) %>%
    group_by(drug) %>%
    filter(!is.na(value)) %>%
    ungroup() %>% 
    rename(auc_recomputed=value) %>%
    mutate(experiment = dataset)
    rez[[dataset]] <- y_new_temp
  eval(parse(text=paste('rm(',dataset,',tempPset, y_new_temp)',sep='')))
}
rez <- rez %>% bind_rows()
```

Calculate number of drugs and cells in overlap.
```{r}
combos <- combn(datasets, 2)
combo_rez <- tibble()
for (combo in 1:ncol(combos)) {
  t_rez <- rez %>% 
    filter(experiment %in% combos[,combo]) %>% 
    spread(key=experiment, value=auc_recomputed) %>% 
    na.omit()
  combo_rez <- tibble(experiment1 = combos[1,combo],
                      experiment2 = combos[2,combo], 
                      common_drugs = t_rez %>% distinct(drug) %>% pull(drug) %>% length(),
                      common_cells = t_rez %>% distinct(cell) %>% pull(cell) %>% length()) %>% 
    bind_rows(combo_rez)
}
for (exp in datasets) {
  t_rez <- rez %>% 
    filter(experiment ==exp) %>% 
    na.omit()
  combo_rez <- tibble(experiment1 = exp,
                      experiment2 = exp,
                      common_drugs = t_rez %>% distinct(drug) %>% pull(drug) %>% length(),
                      common_cells = t_rez %>% distinct(cell) %>% pull(cell) %>% length()) %>%
    bind_rows(combo_rez)
}
```

Common drugs.
```{r}
combo_rez %>% 
  bind_rows(combo_rez %>% mutate(experiment3 = experiment2,
                                 experiment2 = experiment1,
                                 experiment1 = experiment3)) %>%
  select(-experiment3) %>% 
  distinct() %>% 
  ggplot(aes(x=experiment1, y=reorder(experiment2, desc(experiment2)), fill=log2(common_drugs))) +
  geom_tile() +
  geom_text(aes(label = round(common_drugs, 1))) +
  scale_fill_distiller(palette = "Reds", direction = 1, breaks=c(4,6,8), labels=c('16','64','256')) +
  theme_classic() +
  labs(x='', y='', fill='') + 
  theme(legend.position='none',
        axis.text.x = element_text(angle=45, hjust=1, size=12),
        axis.text.y = element_text(angle=45, hjust=1, size=12)) +
  guides(fill = guide_colourbar(ticks = FALSE))
ggsave('plot.pdf',width=6,height=6,units='in')
```

Common cells.
```{r}
combo_rez %>% 
  bind_rows(combo_rez %>% mutate(experiment3 = experiment2,
                                 experiment2 = experiment1,
                                 experiment1 = experiment3)) %>%
  select(-experiment3) %>% 
  distinct() %>% 
  ggplot(aes(x=experiment1, y=reorder(experiment2, desc(experiment2)), fill=log2(common_cells))) +
  geom_tile() +
  geom_text(aes(label = round(common_cells, 1))) +
  scale_fill_distiller(palette = "Reds", direction = 1, breaks=c(6,8,10),labels=c('64','256','1024')) +
  theme_classic() +
  labs(x='', y='', fill='') + 
  theme(legend.position='none',
        axis.text.x = element_text(angle=45, hjust=1, size=12),
        axis.text.y = element_text(angle=45, hjust=1, size=12)) +
  guides(fill = guide_colourbar(ticks = FALSE))
ggsave('plot.pdf',width=6,height=6,units='in')
```

Count of distinct drugs and cells.
```{r}
print(length(unique(rez$drug)))
print(length(unique(rez$cell)))
```

