---
title: "Prep viabilities"
author: "Matt Ploenzke"
date: "1/27/2020"
output: html_document:
  toc: true
  toc_float: true
  code_folding: hide 
---

This joins all the dose-response viability data.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages.
```{r}
library(tidyverse)
library(PharmacoGx)
```

Set options for the run.
```{r}
comparison <- "CCLE_GDSC1000_CTRPv2_FIMM_gCSI"
#comparison <- 'CCLE_GDSC'
run_on_cluster <- TRUE # run on cluster (TRUE) or run locally (FALSE)
drug <- 'Crizotinib'
```

Load posterior.
```{r}
if (!run_on_cluster) {
  posterior <- readRDS(file.path('~/Desktop/Concordance/results',
                                        paste(comparison,'_fit_joint',sep=''),
                                        'posterior.formatted.RDS')) 
} else {
  posterior <- readRDS(file.path('~/concordance',
                                        paste(comparison,'_fit_joint',sep=''),
                                        'posterior.formatted.RDS'))
}
datasets <- posterior %>% distinct(experiment) %>% pull()
```

Load dose-response info.
```{r}
rez <- list()
for (dataset in datasets) {
  print(dataset)
  if (!run_on_cluster) {
    load(file.path('~/Desktop/Concordance/PSets',paste(dataset,'RData',sep='.')))
  } else {
    load(file.path('~/concordance/PSets',paste(dataset,'RData',sep='.')))
  }
}
```

Format dose response data for CCLE.
```{r}
CCLE_sens <- rownames_to_column(as.data.frame(CCLE@sensitivity$raw)) %>% 
  as_tibble() %>% 
  filter(str_detect(rowname,'drugid_PF2341066')) %>%
  separate(rowname, into=c('v1','v2','v3'),sep='_') %>%
  select(-v1) %>%
  rename(drug = v2, cell = v3) %>%
  mutate(drug = 'Crizotinib') %>%
  mutate(study='CCLE')

CCLE_doses <- CCLE_sens %>% 
  select(drug, cell, study, contains('Dose',ignore.case=FALSE)) %>% 
  gather('var','Dose',-drug,-cell,-study) %>%
  mutate(var = gsub('doses','',var)) %>%
  mutate(var = gsub('.Dose','',var)) %>% 
  mutate(var = as.numeric(var)) %>% 
  arrange(cell) %>%
  rename(Concentration = Dose, Dose = var) %>%
  mutate(Concentration = as.numeric(Concentration))

CCLE_viabilities <- CCLE_sens %>% 
  select(drug, cell, study, contains('Viability',ignore.case=FALSE)) %>% 
  gather('var','Viability',-drug,-cell,-study) %>%
  mutate(var = gsub('doses','',var)) %>%
  mutate(var = gsub('.Viability','',var)) %>% 
  mutate(var = as.numeric(var)) %>% 
  arrange(cell) %>%
  rename(Dose = var) %>%
  mutate(Viability = as.numeric(Viability))

CCLE_sens <- CCLE_doses %>% 
  left_join(CCLE_viabilities, by=c('drug','cell','study','Dose')) 
```

Repeat for GDSC1000.
```{r}
GDSC1000_sens <- rownames_to_column(as.data.frame(GDSC1000@sensitivity$raw)) %>% 
  as_tibble() %>% 
  separate(rowname, into=c('v1','v2','v3'),fill='right',sep='_') %>% 
  filter(str_detect(v2,'37') | str_detect(v2,'37')) %>%
    mutate(v1 = case_when(!is.na(v3) ~ paste(v1, v2, sep='_'),
                        TRUE ~ v1), 
         v2 = case_when(!is.na(v3) ~ v3,
                        TRUE ~ v2)) %>% 
  select(-v3) %>%
  rename(cell = v1, drug=v2) %>%
  mutate(drug = 'Crizotinib') %>%
  mutate(study='GDSC1000')

GDSC1000_doses <- GDSC1000_sens %>% 
  select(drug, cell, study, contains('Dose',ignore.case=FALSE)) %>% 
  gather('var','Dose',-drug,-cell,-study) %>%
  mutate(var = gsub('doses_','',var)) %>%
  mutate(var = gsub('.Dose','',var)) %>% 
  mutate(var = as.numeric(var)) %>% 
  arrange(cell) %>%
  rename(Concentration = Dose, Dose = var) %>%
  mutate(Concentration = as.numeric(Concentration))

GDSC1000_viabilities <- GDSC1000_sens %>% 
  select(drug, cell, study, contains('Viability',ignore.case=FALSE)) %>% 
  gather('var','Viability',-drug,-cell,-study) %>%
  mutate(var = gsub('doses_','',var)) %>%
  mutate(var = gsub('.Viability','',var)) %>% 
  mutate(var = as.numeric(var)) %>% 
  arrange(cell) %>%
  rename(Dose = var) %>%
  mutate(Viability = as.numeric(Viability))

GDSC1000_sens <- GDSC1000_doses %>% 
  left_join(GDSC1000_viabilities, by=c('drug','cell','study','Dose')) 
```

Repeat for CTRPv2.
```{r}  
CTRPv2_sens <- rownames_to_column(as.data.frame(CTRPv2@sensitivity$raw)) %>% 
  as_tibble() %>% 
  filter(str_detect(rowname,'Crizotinib')) %>%
  separate(rowname, into=c('v1','v2','v3','v4'),sep='_') %>%
  rename(drug = v2, cell = v1) %>%
  select(-v3, -v4) %>%
  mutate(study = 'CTRPv2')

CTRPv2_doses <- CTRPv2_sens %>% 
  select(drug, cell, study, contains('Dose',ignore.case=FALSE)) %>% 
  gather('var','Dose',-drug,-cell,-study) %>%
  mutate(var = gsub('dose','',var)) %>%
  mutate(var = gsub('.Dose','',var)) %>% 
  mutate(var = as.numeric(var)) %>% 
  arrange(cell) %>%
  rename(Concentration = Dose, Dose = var) %>%
  mutate(Concentration = as.numeric(Concentration))

CTRPv2_viabilities <- CTRPv2_sens %>% 
  select(drug, cell, study, contains('Viability',ignore.case=FALSE)) %>% 
  gather('var','Viability',-drug,-cell,-study) %>%
  mutate(var = gsub('dose','',var)) %>%
  mutate(var = gsub('.Viability','',var)) %>% 
  mutate(var = as.numeric(var)) %>% 
  arrange(cell) %>%
  rename(Dose = var) %>%
  mutate(Viability = as.numeric(Viability))

CTRPv2_sens <- CTRPv2_doses %>% 
  left_join(CTRPv2_viabilities, by=c('drug','cell','study','Dose')) 
```

Repeat for FIMM.
```{r}
FIMM_sens <- rownames_to_column(as.data.frame(FIMM@sensitivity$raw)) %>% 
  as_tibble() %>% 
  filter(str_detect(rowname,'Crizotinib')) %>%
  separate(rowname, into=c('v1','v2'),sep='_') %>%
  rename(drug = v1, cell = v2) %>%
  mutate(study = 'FIMNM')

FIMM_doses <- FIMM_sens %>% 
  select(drug, cell, study, contains('.Dose',ignore.case=FALSE)) %>% 
  gather('var','Dose',-drug,-cell,-study) %>%
  mutate(var = gsub('.Dose','',var)) %>%
  mutate(var = gsub('Dose','',var)) %>% 
  mutate(var = as.numeric(var)) %>%  
  arrange(cell) %>%
  rename(Concentration = Dose, Dose = var) %>%
  mutate(Concentration = as.numeric(Concentration))

FIMM_viabilities <- FIMM_sens %>% 
  select(drug, cell, study, contains('Viability',ignore.case=FALSE)) %>% 
  gather('var','Viability',-drug,-cell,-study) %>%
  mutate(var = gsub('Dose','',var)) %>%
  mutate(var = gsub('.Viability','',var)) %>% 
  mutate(var = as.numeric(var)) %>% 
  arrange(cell) %>%
  rename(Dose = var) %>%
  mutate(Viability = as.numeric(Viability))

FIMM_sens <- FIMM_doses %>% 
  left_join(FIMM_viabilities, by=c('drug','cell','study','Dose')) 
```

Repeat for gCSI.
```{r}
gCSI_sens <- rownames_to_column(as.data.frame(gCSI@sensitivity$raw)) %>% 
  as_tibble() %>% 
  filter(str_detect(rowname,'Crizotinib')) %>%
  separate(rowname, into=c('v1','v2'),sep='_') %>%
  rename(drug = v2, cell = v1) %>%
  mutate(study = 'gCSI')

gCSI_doses <- gCSI_sens %>% 
  select(drug, cell, study, contains('.Dose',ignore.case=FALSE)) %>% 
  gather('var','Dose',-drug,-cell,-study) %>%
  mutate(var = gsub('.Dose','',var)) %>%
  mutate(var = gsub('Dose ','',var)) %>% 
  mutate(var = as.numeric(var)) %>%  
  arrange(cell) %>%
  rename(Concentration = Dose, Dose = var) %>%
  mutate(Concentration = as.numeric(Concentration))

gCSI_viabilities <- gCSI_sens %>% 
  select(drug, cell, study, contains('Viability',ignore.case=FALSE)) %>% 
  gather('var','Viability',-drug,-cell,-study) %>%
  mutate(var = gsub('Dose ','',var)) %>%
  mutate(var = gsub('.Viability','',var)) %>% 
  mutate(var = as.numeric(var)) %>% 
  arrange(cell) %>%
  rename(Dose = var) %>%
  mutate(Viability = as.numeric(Viability))

gCSI_sens <- gCSI_doses %>% 
  left_join(gCSI_viabilities, by=c('drug','cell','study','Dose')) 
```

Merge and save.
```{r}
viability_data <- CCLE_sens %>% 
  bind_rows(GDSC1000_sens) %>%
  bind_rows(CTRPv2_sens) %>%
  bind_rows(FIMM_sens) %>%
  bind_rows(gCSI_sens) %>%
  left_join(posterior, by=c('drug','cell','study'='experiment')) %>%
  na.omit()
save(viability_data,file='viability_data.RData')
```
