---
title: "Gene fusion comparison"
author: "Matt Ploenzke"
date: "1/24/2020"
output: html_document:
  toc: true
  toc_float: true
  code_folding: hide 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages.
```{r}
library(readxl)
library(tidyverse)
library(PharmacoGx)
```

Set options for the run.
```{r}
comparison <- "CCLE_GDSC1000_CTRPv2_FIMM_gCSI"
#comparison <- 'CCLE_GDSC'
min_posterior_probability_sensitive <- .5 # minimum posterior probability for denoting a cell is sensitive
mean_common_cells <- TRUE # reduce joint dataset to mean sensitivity measure 
```

Load posterior and fusions (https://www.nature.com/articles/s41467-019-09940-1#Sec25 supplementary table 2).
```{r}
posterior <- readRDS(file.path('~/Desktop/Concordance/results',
                                        paste(comparison,'_fit_joint',sep=''),
                                        'posterior.formatted.RDS')) %>% 
  filter(drug == 'Crizotinib')
annotations <- read_excel("~/Desktop/Concordance/PSets/41467_2019_9940_MOESM5_ESM.xlsx") %>% 
  filter(str_detect(`Fusion Name`,'ALK'))
```

Join and plot posterior versus realized values colored by number of experiments.
```{r}
expit <- function(x) {return(1/(1+exp(-x)))}
tdat <- posterior 
tdat %>%
  ggplot(aes(x=realized_value, y=posterior_probability_sensitive, color=num_experiments)) + 
  geom_point(size=3,alpha=.75) + 
  geom_hline(aes(yintercept=.5),lty=2) +
  geom_vline(aes(xintercept=.2),lty=2,alpha=.5,color='red') + 
  geom_smooth(data=subset(posterior, num_experiments==1), method = "nls", method.args = list(formula = y ~ expit(a*x+b), start = list(a=0,b=0)),se = FALSE,color='black') +
  facet_grid(cols=vars(experiment)) +
  theme_bw() + 
  theme(legend.position='bottom') + 
  guides(color=guide_legend(title="Number experiments")) + 
  labs(title='Crizotinib posterior cell sensitivity',x='AAC',y='Model-based') + 
  scale_x_continuous(limits = c(0,1),breaks = c(0,.5,1)) + 
  scale_color_viridis_c(direction = -1)
ggsave('plot.pdf',width=16,height=5,units='in')
```

Join and plot posterior versus realized values colored by fusion.
```{r}
library(scales)
expit <- function(x) {return(1/(1+exp(-x)))}
tdat <- posterior %>% 
  left_join(annotations %>% filter(`Fusion Name` %in% c('EML4--ALK', 'NPM1--ALK')), by=c('cell'='Cell Line'))
tdat2 <- tdat %>% filter(!is.na(`Fusion Name`))
tdat %>%
  filter(is.na(`Fusion Name`)) %>%
  mutate(`Fusion Name` = 'NA') %>%
  ggplot(aes(x=realized_value, y=posterior_probability_sensitive)) + 
  geom_point(fill='grey',color='grey',size=3,alpha=.4,shape=21) + 
  geom_point(data=tdat2, aes(fill=`Fusion Name`),color='black',size=3,alpha=1, shape=21) + 
  geom_hline(aes(yintercept=.5),lty=2) +
  #geom_vline(aes(xintercept=.2),lty=2,alpha=.5,color='red') + 
  #geom_smooth(data=subset(posterior, num_experiments==1), method = "nls", method.args = list(formula = y ~ expit(a*x+b), start = list(a=0,b=0)),se = FALSE,color='black') +
  facet_grid(cols=vars(experiment)) +
  theme_bw() + 
  theme(legend.position='top',
        panel.grid = element_blank(),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14),
        legend.text = element_text(size=14),
        legend.title = element_text(size=14),
        plot.title = element_blank()) +
  guides(fill=guide_legend(title="Fusion")) + 
  labs(title='Crizotinib posterior cell sensitivity colored by NSCLC known fusions',x='AAC',y='Estimated probability sensitive') + 
  scale_x_continuous(breaks=c(0,.5,1), limits = c(0,1)) + 
  scale_y_continuous(breaks=c(0,.5,1), limits = c(0,1)) + 
  scale_fill_manual(values = c('NA'='grey','EML4--ALK'='black','NPM1--ALK'='red'))
ggsave('temp.png',width=14,height=4,units='in')
```

