---
title: "Make figures"
author: "Matt Ploenzke"
date: "2/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages needed.
```{r}
rm(list=ls(all=TRUE))
library(tidyverse)
library(cowplot)
```

Combine posterior agreement plot with individual densities for CCLE GDSC comparison.
```{r}
base_path <- file.path('~/Desktop/Concordance/results/CCLE_GDSC_fit_p60/auc_recomputed')
drugs <- c('17AAG','AZD0530','AZD6244','Crizotinib','Erlotinib','lapatinib','Nilotinib','Nutlin3','paclitaxel',
           'PD0325901','PD0332991','PHA665752','PLX4720','Sorafenib','TAE684')
drugs <- c('lapatinib','nilotinib')
for (drug in drugs) {
    #p_main <- readRDS(file.path(base_path,'CCLE_GDSC','by_drug',paste(drug,'_2way_CCLE_GDSC.RDS',sep='')))
    #p_main$data$agreement <- 1
    p_main <- p_main + 
      #scale_colour_gradient2(midpoint=.5,limits = c(0,1),mid='grey50',breaks=c(0,0.5,1),labels=c(0,0.5,1)) + 
      theme(legend.position = c(.1,.65), 
            plot.title=element_blank()) + 
      #theme(legend.position='none') + 
      theme(axis.title = element_text(size = 14),
            axis.text = element_text(size = 12))
    p_top <- readRDS(file.path(base_path,'CCLE','fitted_densities_by_drug',paste(drug,'.RDS',sep=''))) 
    p_top$layers <- rev(p_top$layers)
    p_top <- p_top + geom_density(fill='black') 
    p_top$layers <- rev(p_top$layers)
    p_top <- p_top + 
      theme(plot.title=element_blank(),
            axis.title = element_blank(),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            panel.border = element_blank(), panel.grid.major = element_blank(),
            panel.grid.minor = element_blank()) +
        scale_color_manual(values = c('resistant'='blue', 'sensitive'='orange')) + 
      scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
      scale_y_continuous(breaks=c(0,1),labels=c('0','1'),limits = c(0,1), name='Density')
    p_side <- readRDS(file.path(base_path,'GDSC','fitted_densities_by_drug',paste(drug,'.RDS',sep='')))
    p_side$layers <- rev(p_side$layers)
    p_side <- p_side + geom_density(fill='black') 
    p_side$layers <- rev(p_side$layers)
    p_side <- p_side + 
      theme(plot.title=element_blank(),
            axis.title = element_blank(),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            panel.border = element_blank(), panel.grid.major = element_blank(),
            panel.grid.minor = element_blank()) +
        scale_color_manual(values = c('resistant'='blue', 'sensitive'='orange')) + 
      scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
      scale_y_continuous(breaks=c(0,1),labels=c('0','1'),limits = c(0,1), name='Density') +
      ggpubr::rotate() 
      #if (drug == 'Erlotinib') {
        tempdat <- p_top$data #%>% filter(value>=.25) 
        p_top <- p_top + 
          scale_x_continuous(breaks = pull(tempdat,value)) +
          theme(axis.ticks.x = element_line(size = .25))
        tempdat <- p_side$data #%>% filter(value>=.25) 
        p_side <- p_side + 
          scale_x_continuous(breaks = pull(tempdat,value)) +
          theme(axis.ticks.y = element_line(size = .25))
    #}
    
    cell_ty <- p_top$layers[[3]]$data %>% distinct(cell_type) %>% pull()
    if ('sensitive' %in% cell_ty & drug=='Crizotinib') {
      p_top$layers[[3]]$data <- p_top$layers[[3]]$data %>% 
        mutate(beta_curve = ifelse(cell_type == 'sensitive',beta_curve*5, beta_curve))
    }
    cell_ty <- p_side$layers[[3]]$data %>% distinct(cell_type) %>% pull()
    if ('sensitive' %in% cell_ty & drug=='Crizotinib') {
      p_side$layers[[3]]$data <- p_side$layers[[3]]$data %>% 
        mutate(beta_curve = ifelse(cell_type == 'sensitive',beta_curve*5, beta_curve)) 
    }
    if ('sensitive' %in% cell_ty & drug=='Nilotinib') {
      p_top$layers[[3]]$data <- p_top$layers[[3]]$data %>% 
        mutate(beta_curve = ifelse(cell_type == 'sensitive',beta_curve*10, beta_curve))
    }
    cell_ty <- p_side$layers[[3]]$data %>% distinct(cell_type) %>% pull()
    if ('sensitive' %in% cell_ty & drug=='Nilotinib') {
      p_side$layers[[3]]$data <- p_side$layers[[3]]$data %>% 
        mutate(beta_curve = ifelse(cell_type == 'sensitive',beta_curve*10, beta_curve)) 
    }
    
    ggdraw() +
      draw_plot(p_main,0,0,.85,.85) +
      draw_plot(p_top,.05,.85,.80,.15) +
      draw_plot(p_side,.85,.05,.15,.80) 
    ggsave(paste(drug,'.png',sep=''),width=8,height=8,units='in')s
}
```

From joint fit.
```{r}
p_top <- readRDS('~/Desktop/Concordance/results/CCLE_GDSC1000_CTRPv2_FIMM_gCSI_fit_joint/auc_recomputed/CCLE_GDSC1000_CTRPv2_FIMM_gCSI/fitted_densities_by_drug/Crizotinib.RDS')
p_top$layers <- rev(p_top$layers)
#`p_top <- p_top + geom_density(fill='black') 
p_top$layers[[2]]$aes_params$alpha <- .2
p_top$layers <- rev(p_top$layers)
p_top + 
  theme(panel.grid = element_blank(),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14),
        plot.title = element_blank()) +
    scale_color_manual(values = c('resistant'='blue', 'sensitive'='orange')) + 
  labs(x='AAC') +
  scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_y_continuous(breaks=c(0,1),labels=c('0','1'),limits = c(0,1), name='Density')
ggsave('temp.png',width=14,height=3,units='in')
```

Combine posterior agreement plot with individual densities from NCI60.
```{r}
base_path <- file.path('~/Desktop/Concordance/results/CTRP_GDSC_NCI60_fit_p50/ic50')
drugs <- c('topotecan','dabrafenib')
drug <- drugs[2]
p_main <- readRDS(file.path(base_path,'GDSC_NCI60','by_drug',paste(drug,'_2way_GDSC_NCI60.RDS',sep=''))) 
p_main <- p_main + 
  theme(legend.position = c(.1,.65), 
        plot.title=element_blank()) + 
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12)) +
  #geom_vline(aes(xintercept=18.15),lty=2) +# CTRP_GDSC dabrafenib
  #geom_hline(aes(yintercept=5.85),lty=2) +# CTRP_GDSC dabrafenib
  #lims(x=c(9.5,30),y=c(3.4,8.25)) # CTRP_GDSC dabrafenib
  geom_vline(aes(xintercept=5.85),lty=2) +# GDSC_NCI60 dabrafenib
  geom_hline(aes(yintercept=-.15),lty=2) +# GDSC_NCI60 dabrafenib
  lims(x=c(3.5,8.5),y=c(-2.5,2.5)) # GDSC_NCI60 dabrafenib
p_top <- readRDS(file.path(base_path,'GDSC','fitted_densities_by_drug',paste(drug,'.RDS',sep=''))) 
p_top$layers <- rev(p_top$layers)
p_top <- p_top + geom_density(fill='black') 
p_top$layers <- rev(p_top$layers)
p_top <- p_top + 
  theme(plot.title=element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
    scale_color_manual(values = c('resistant'='blue', 'sensitive'='orange')) #+ 
p_side <- readRDS(file.path(base_path,'NCI60','fitted_densities_by_drug',paste(drug,'.RDS',sep='')))
p_side$layers <- rev(p_side$layers)
p_side <- p_side + geom_density(fill='black') 
p_side$layers <- rev(p_side$layers)
p_side <- p_side + 
  theme(plot.title=element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
    scale_color_manual(values = c('resistant'='blue', 'sensitive'='orange')) + 
  ggpubr::rotate() 
tempdat <- p_top$data 
p_top <- p_top + 
  #scale_x_continuous(breaks = pull(tempdat,value), limits=c(9.5,30)) + # CTRP_GDSC 
  scale_x_continuous(breaks = pull(tempdat,value), limits=c(3.5,8.5)) + # GDSC_NCI60 
  theme(axis.ticks.x = element_line(size = .25))
tempdat <- p_side$data
p_side <- p_side + 
  #scale_x_continuous(breaks = pull(tempdat,value), limits=c(3.4,8.25)) + # CTRP_GDSC 
  scale_x_continuous(breaks = pull(tempdat,value), limits=c(-2.5,2.5)) + # GDSC_NCI60 
  theme(axis.ticks.y = element_line(size = .25))

ggdraw() +
  draw_plot(p_main,0,0,.85,.85) +
  draw_plot(p_top,.05,.85,.80,.15) +
  draw_plot(p_side,.85,.05,.15,.80) 
ggsave(paste(drug,'.png',sep=''),width=8,height=8,units='in')

```

Combine posteriors for PRISM comparisons.
```{r}
base_path <- file.path('~/Desktop/Concordance/results/PRISM_GDSC_CTRP_fit/auc')
#base_path <- file.path('~/Desktop/Concordance/results/PRISM_GDSC_CTRP_fit_overlap/aac')
drugs <- c('lapatinib','nilotinib')
comps <- c('CTRP_GDSC','CTRP_PRISM','GDSC_PRISM')
for (drug in drugs) {
  for (comp in comps) {
    study1 <- strsplit(comp,split='_')[[1]][1]
    study2 <- strsplit(comp,split='_')[[1]][2]
    p_main <- readRDS(file.path(base_path,comp,'by_drug',paste(drug,'_2way_',study1,'_',study2,'.RDS',sep='')))
    #p_main$data$agreement <- 1
    p_main <- p_main + 
      #scale_colour_gradient2(midpoint=.5,limits = c(0,1),mid='grey50',breaks=c(0,0.5,1),labels=c(0,0.5,1)) + 
      theme(legend.position = c(.1,.65), 
            plot.title=element_blank()) + 
      #theme(legend.position='none') + 
      theme(axis.title = element_text(size = 14),
            axis.text = element_text(size = 12))
    p_top <- readRDS(file.path(base_path,study1,'fitted_densities_by_drug',paste(drug,'.RDS',sep=''))) 
    p_top$layers <- rev(p_top$layers)
    p_top <- p_top + geom_density(fill='black') 
    p_top$layers <- rev(p_top$layers)
    p_top <- p_top + 
      theme(plot.title=element_blank(),
            axis.title = element_blank(),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            panel.border = element_blank(), panel.grid.major = element_blank(),
            panel.grid.minor = element_blank()) +
        scale_color_manual(values = c('resistant'='blue', 'sensitive'='orange')) + 
      scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
      scale_y_continuous(breaks=c(0,1),labels=c('0','1'),limits = c(0,1), name='Density')
    p_side <- readRDS(file.path(base_path,study2,'fitted_densities_by_drug',paste(drug,'.RDS',sep='')))
    p_side$layers <- rev(p_side$layers)
    p_side <- p_side + geom_density(fill='black') 
    p_side$layers <- rev(p_side$layers)
    p_side <- p_side + 
      theme(plot.title=element_blank(),
            axis.title = element_blank(),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            panel.border = element_blank(), panel.grid.major = element_blank(),
            panel.grid.minor = element_blank()) +
        scale_color_manual(values = c('resistant'='blue', 'sensitive'='orange')) + 
      scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
      scale_y_continuous(breaks=c(0,1),labels=c('0','1'),limits = c(0,1), name='Density') +
      ggpubr::rotate() 
      tempdat <- p_top$data #%>% filter(value>=.25) 
      p_top <- p_top + 
        scale_x_continuous(breaks = pull(tempdat,value)) +
        theme(axis.ticks.x = element_line(size = .25))
      tempdat <- p_side$data #%>% filter(value>=.25) 
      p_side <- p_side + 
        scale_x_continuous(breaks = pull(tempdat,value)) +
        theme(axis.ticks.y = element_line(size = .25))
    ggdraw() +
      draw_plot(p_main,0,0,.85,.85) +
      draw_plot(p_top,.05,.85,.80,.15) +
      draw_plot(p_side,.85,.05,.15,.80) 
    ggsave(paste(drug,'_',comp,'.png',sep=''),width=8,height=8,units='in')
  }
}
```