---
title: "Waterfall comparison"
author: "Matt Ploenzke"
date: "1/27/2020"
output: html_document:
  toc: true
  toc_float: true
  code_folding: hide 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages.
```{r}
library(tidyverse)
library(PharmacoGx)
```

Set options for the run.
```{r}
min_posterior_probability_sensitive <- .5 # minimum posterior probability for denoting a cell is sensitive
min_aac_sensitive <- .2 # minimum AAC for denoting a cell is sensitive
mean_common_cells <- TRUE # reduce joint dataset to mean sensitivity measure (TRUE) or include individual study measures (FALSE)
include_all_cells <- TRUE # plot all cells (TRUE) or restrict to those called differently by method (FALSE)
dir.create('dose_response_curves',showWarnings = FALSE)
```

Function definitions.
```{r}
GetSupportVec <- function(x, output_length = 101) {return(seq(from = min(x), to = max(x), length.out = output_length))}
Hill <- function(x, pars) {return(pars[2] + (1 - pars[2]) / (1 + (10 ^ x / 10 ^ pars[3]) ^ pars[1]))}
```

Load data.
```{r}
load('~/Desktop/Concordance/results/viability_data.RData')
```

Binarize sensitivities and optionally filter.
```{r}
if (mean_common_cells) {
  viability_data <- viability_data %>% 
    na.omit() %>%
    group_by(cell) %>% 
    mutate(realized_value = mean(realized_value,na.rm=TRUE),
           posterior_probability_sensitive = mean(posterior_probability_sensitive, na.rm=TRUE)) %>%
    ungroup()
} else {
 viability_data <- viability_data %>%
   na.omit() %>%
   unite(cell, cell, study) %>%
   select(-drug)
}
viability_data <- viability_data %>%
    mutate(posterior_cell_type = case_when(posterior_probability_sensitive >= min_posterior_probability_sensitive ~ 'sensitive',
                                 TRUE ~ 'resistant'),
           aac_cell_type = case_when(realized_value >= min_aac_sensitive ~ 'sensitive',
                                 TRUE ~ 'resistant'))
if (!include_all_cells) {
    viability_data <- viability_data %>%
      filter(posterior_cell_type != aac_cell_type)
}
```

Calculate dose-response curve fits.
```{r}
random_cells <- viability_data %>%
  distinct(cell) %>% 
  sample_n(1) %>% 
  pull()

fit_params <- viability_data %>%
  filter(cell %in% random_cells) %>%
  group_by(drug, cell, study) %>%
  arrange(Concentration)
  do(fit = logLogisticRegression(conc=.$Concentration,viability=.$Viability,
                                 conc_as_log = FALSE,family='normal',trunc=TRUE, viability_as_pct = TRUE)) %>%
  ungroup() %>%
  unnest(fit) %>% 
  mutate(fit=unlist(fit)) %>%
  group_by(drug, cell, study) %>%
  mutate(param = case_when(row_number() == 1 ~ 'HS',
                           row_number() == 2 ~ 'E_inf',
                           row_number() == 3 ~ 'EC50')) %>%
  spread(param, fit)

log10_x_vals <- viability_data %>%
  filter(cell %in% random_cells) %>%
  group_by(drug, cell, study) %>%
  do(vals = GetSupportVec(log10(.$Concentration))) %>%
  ungroup() %>%
  unnest(vals)

curve_values <- log10_x_vals %>%
  left_join(fit_params, by=c('drug','cell','study')) %>%
  mutate(predicted = Hill(vals, pars = c(HS, E_inf/100, EC50))*100) %>%
  mutate(concentration = 10^vals)
```

```{r}
curve_values %>%
  ggplot(aes(x=concentration, y=predicted, color=cell)) + 
  geom_hline(aes(yintercept=0), lty=1,color='grey') + 
  geom_hline(aes(yintercept=100), lty=1, color='grey') + 
  geom_line() + 
  scale_x_continuous(trans='log10') + 
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"))
```

```{r}
viability_data %>%
  filter(cell %in% random_cells) %>%
  ggplot(aes(x=Concentration, y=Viability, color=cell)) + 
  geom_hline(aes(yintercept=0), lty=1,color='grey') + 
  geom_hline(aes(yintercept=100), lty=1, color='grey') + 
  geom_point() + 
  scale_x_continuous(trans='log10') + 
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black")) + 
  facet_wrap(vars(study))
```


Plot dose-response points and curves.
```{r}
    p <- points_data %>%
      ggplot(aes(x=concentrations,y=value, color=study)) +
        geom_point() +
        geom_line(data=preds_data,aes(x=concentrations,y=value, color=study),show.legend=FALSE) + 
        geom_hline(aes(yintercept=0), lty=1,color='grey') + 
        geom_hline(aes(yintercept=100), lty=1, color='grey') + 
        scale_x_continuous(trans='log10') + 
        labs(y = "Relative cell viability",
             x = expression(paste("Dose Concentration (", log10, " ", mu, "M)",sep='')),
             color='') + 
        scale_y_continuous(limits=c(0,110),
                           breaks=seq(0,100,by=20)) + 
      ggtitle(paste(drug,'; ', curr_cell,sep=''), 
              subtitle = paste('Posterior: ',posterior %>% filter(cell==curr_cell) %>% pull(posterior_probability_sensitive) %>% round(digits = 2), '; ',
                               'AAC: ', posterior %>% filter(cell==curr_cell) %>% pull(realized_value) %>% round(digits=2),sep=''))
    ggsave(plot=p, filename=file.path('dose_response_curves',paste(curr_cell,'.png',sep='')))
}
```
